pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
        sh 'echo "Compiling ... "'
        sh 'javac HelloWorld.java'
        sh 'echo "Execution ..."'
        sh 'java HelloWorld'
        sh 'jar cvfe HelloWorld.jar HelloWorld *.class'
        sh 'echo "============================"'
        sh '#Execution:'
        sh 'java -jar HelloWorld.jar'
        sh 'echo "============================"'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
  }
}
