pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        sh 'mvn --version'
        sh 'echo "Compiling ... "'
        sh 'javac simple_java_app.java'
        sh 'echo "Execution ..."'
        sh 'java simple_java_app'
        sh 'jar cvfe simple_java_app.jar simple_java_app *.class'
        sh 'echo "============================"'
        sh '#Execution:'
        sh 'java -jar simple_java_app.jar'
        sh 'echo "============================"'
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        sh 'node --version'
      }
    }
  }
}
